name: qr_code
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.4.1
  firebase_auth: 4.2.5
  lottie: ^2.2.0
  cloud_firestore: 4.3.1
  qr_flutter: 4.0.0
  flutter_spinkit: ^5.1.0
  open_file: 3.2.1
  path_provider: 2.0.11
  pdf: 3.6.4
  flutter_barcode_scanner: 2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - asset/lottie/113880-verification.json
