// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBLdKmfFzMa4k7MmlNfTTkWInUcJHkXi8',
    appId: '1:967905357000:android:30e567a8aa30d54f6909fd',
    messagingSenderId: '967905357000',
    projectId: 'qr-code-me',
    storageBucket: 'qr-code-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuV3wfmatOKMtG-0RU27DcFIUH1LzwUZA',
    appId: '1:967905357000:ios:618f38a4512a63706909fd',
    messagingSenderId: '967905357000',
    projectId: 'qr-code-me',
    storageBucket: 'qr-code-me.appspot.com',
    iosClientId: '967905357000-oh3adfpts5tpfbe464mq0pnm0ok2idsf.apps.googleusercontent.com',
    iosBundleId: 'com.xaiur.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuV3wfmatOKMtG-0RU27DcFIUH1LzwUZA',
    appId: '1:967905357000:ios:618f38a4512a63706909fd',
    messagingSenderId: '967905357000',
    projectId: 'qr-code-me',
    storageBucket: 'qr-code-me.appspot.com',
    iosClientId: '967905357000-oh3adfpts5tpfbe464mq0pnm0ok2idsf.apps.googleusercontent.com',
    iosBundleId: 'com.xaiur.qrCode',
  );
}
